name: Test and Deploy

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Specify the Node.js version
        continue-on-error: false

      - name: Install dependencies
        run: npm install
        continue-on-error: false

      - name: Run Tailwind CSS
        run: npx tailwindcss -i ./src/styles/style.css -o ./src/styles/output.css
        continue-on-error: false

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: ${{ needs.test.result == 'success' }}
    steps:
      - name: Deploy to remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_DEV_HOST }}
          username: ${{ secrets.SSH_DEV_USERNAME }}
          port: ${{ secrets.SSH_DEV_PORT }}
          key: ${{ secrets.SSH_DEV_PRIVATE_KEY }}
          script: deploy-frontend.sh
        continue-on-error: false
